"""
app_data.py — shared static data (screener stock lists, sector metadata).
Imported by main.py so the screener endpoint has access to the stock list
without duplicating it across Python and TypeScript.
"""

SCREENER_STOCKS: dict[str, list[dict]] = {
    "Technology": [
        {"ticker": "AAPL",  "name": "Apple Inc."},
        {"ticker": "MSFT",  "name": "Microsoft Corp."},
        {"ticker": "NVDA",  "name": "NVIDIA Corp."},
        {"ticker": "GOOGL", "name": "Alphabet Inc."},
        {"ticker": "META",  "name": "Meta Platforms Inc."},
        {"ticker": "AVGO",  "name": "Broadcom Inc."},
        {"ticker": "AMD",   "name": "Advanced Micro Devices"},
        {"ticker": "INTC",  "name": "Intel Corp."},
        {"ticker": "ORCL",  "name": "Oracle Corp."},
        {"ticker": "CRM",   "name": "Salesforce Inc."},
        {"ticker": "ADBE",  "name": "Adobe Inc."},
        {"ticker": "CSCO",  "name": "Cisco Systems"},
        {"ticker": "QCOM",  "name": "QUALCOMM Inc."},
        {"ticker": "TXN",   "name": "Texas Instruments"},
        {"ticker": "AMAT",  "name": "Applied Materials"},
        {"ticker": "MU",    "name": "Micron Technology"},
    ],
    "Healthcare": [
        {"ticker": "UNH",   "name": "UnitedHealth Group"},
        {"ticker": "LLY",   "name": "Eli Lilly and Co."},
        {"ticker": "JNJ",   "name": "Johnson & Johnson"},
        {"ticker": "ABBV",  "name": "AbbVie Inc."},
        {"ticker": "MRK",   "name": "Merck & Co."},
        {"ticker": "PFE",   "name": "Pfizer Inc."},
        {"ticker": "TMO",   "name": "Thermo Fisher Scientific"},
        {"ticker": "ABT",   "name": "Abbott Laboratories"},
        {"ticker": "DHR",   "name": "Danaher Corp."},
        {"ticker": "BMY",   "name": "Bristol-Myers Squibb"},
        {"ticker": "AMGN",  "name": "Amgen Inc."},
        {"ticker": "ISRG",  "name": "Intuitive Surgical"},
        {"ticker": "SYK",   "name": "Stryker Corp."},
        {"ticker": "REGN",  "name": "Regeneron Pharmaceuticals"},
        {"ticker": "VRTX",  "name": "Vertex Pharmaceuticals"},
    ],
    "Financials": [
        {"ticker": "JPM",   "name": "JPMorgan Chase"},
        {"ticker": "V",     "name": "Visa Inc."},
        {"ticker": "MA",    "name": "Mastercard Inc."},
        {"ticker": "BAC",   "name": "Bank of America"},
        {"ticker": "WFC",   "name": "Wells Fargo"},
        {"ticker": "GS",    "name": "Goldman Sachs"},
        {"ticker": "MS",    "name": "Morgan Stanley"},
        {"ticker": "AXP",   "name": "American Express"},
        {"ticker": "BLK",   "name": "BlackRock Inc."},
        {"ticker": "SPGI",  "name": "S&P Global Inc."},
        {"ticker": "C",     "name": "Citigroup Inc."},
        {"ticker": "CB",    "name": "Chubb Ltd."},
        {"ticker": "PNC",   "name": "PNC Financial Services"},
        {"ticker": "SCHW",  "name": "Charles Schwab Corp."},
        {"ticker": "ICE",   "name": "Intercontinental Exchange"},
    ],
    "Energy": [
        {"ticker": "XOM",   "name": "Exxon Mobil Corp."},
        {"ticker": "CVX",   "name": "Chevron Corp."},
        {"ticker": "COP",   "name": "ConocoPhillips"},
        {"ticker": "EOG",   "name": "EOG Resources"},
        {"ticker": "SLB",   "name": "SLB (Schlumberger)"},
        {"ticker": "MPC",   "name": "Marathon Petroleum"},
        {"ticker": "PSX",   "name": "Phillips 66"},
        {"ticker": "VLO",   "name": "Valero Energy"},
        {"ticker": "OXY",   "name": "Occidental Petroleum"},
        {"ticker": "DVN",   "name": "Devon Energy"},
        {"ticker": "HAL",   "name": "Halliburton Co."},
        {"ticker": "BKR",   "name": "Baker Hughes"},
    ],
    "Consumer Discretionary": [
        {"ticker": "AMZN",  "name": "Amazon.com Inc."},
        {"ticker": "TSLA",  "name": "Tesla Inc."},
        {"ticker": "HD",    "name": "Home Depot Inc."},
        {"ticker": "MCD",   "name": "McDonald's Corp."},
        {"ticker": "NKE",   "name": "Nike Inc."},
        {"ticker": "SBUX",  "name": "Starbucks Corp."},
        {"ticker": "TJX",   "name": "TJX Companies"},
        {"ticker": "LOW",   "name": "Lowe's Companies"},
        {"ticker": "CMG",   "name": "Chipotle Mexican Grill"},
        {"ticker": "GM",    "name": "General Motors"},
        {"ticker": "BKNG",  "name": "Booking Holdings"},
        {"ticker": "RCL",   "name": "Royal Caribbean Group"},
        {"ticker": "MAR",   "name": "Marriott International"},
    ],
    "Consumer Staples": [
        {"ticker": "WMT",   "name": "Walmart Inc."},
        {"ticker": "COST",  "name": "Costco Wholesale"},
        {"ticker": "PG",    "name": "Procter & Gamble"},
        {"ticker": "KO",    "name": "Coca-Cola Co."},
        {"ticker": "PEP",   "name": "PepsiCo Inc."},
        {"ticker": "PM",    "name": "Philip Morris Intl."},
        {"ticker": "MO",    "name": "Altria Group"},
        {"ticker": "MDLZ",  "name": "Mondelez International"},
        {"ticker": "CL",    "name": "Colgate-Palmolive"},
        {"ticker": "GIS",   "name": "General Mills"},
    ],
    "Industrials": [
        {"ticker": "GE",    "name": "GE Aerospace"},
        {"ticker": "CAT",   "name": "Caterpillar Inc."},
        {"ticker": "UNP",   "name": "Union Pacific Corp."},
        {"ticker": "HON",   "name": "Honeywell Intl."},
        {"ticker": "RTX",   "name": "RTX Corp."},
        {"ticker": "BA",    "name": "Boeing Co."},
        {"ticker": "LMT",   "name": "Lockheed Martin"},
        {"ticker": "DE",    "name": "Deere & Co."},
        {"ticker": "UPS",   "name": "United Parcel Service"},
        {"ticker": "FDX",   "name": "FedEx Corp."},
        {"ticker": "WM",    "name": "Waste Management"},
        {"ticker": "EMR",   "name": "Emerson Electric"},
        {"ticker": "GD",    "name": "General Dynamics"},
        {"ticker": "NOC",   "name": "Northrop Grumman"},
    ],
    "Communication Services": [
        {"ticker": "GOOGL", "name": "Alphabet Inc."},
        {"ticker": "META",  "name": "Meta Platforms Inc."},
        {"ticker": "NFLX",  "name": "Netflix Inc."},
        {"ticker": "DIS",   "name": "Walt Disney Co."},
        {"ticker": "CMCSA", "name": "Comcast Corp."},
        {"ticker": "T",     "name": "AT&T Inc."},
        {"ticker": "VZ",    "name": "Verizon Communications"},
        {"ticker": "TMUS",  "name": "T-Mobile US"},
        {"ticker": "CHTR",  "name": "Charter Communications"},
    ],
    "Materials": [
        {"ticker": "LIN",   "name": "Linde PLC"},
        {"ticker": "APD",   "name": "Air Products"},
        {"ticker": "SHW",   "name": "Sherwin-Williams"},
        {"ticker": "FCX",   "name": "Freeport-McMoRan"},
        {"ticker": "NEM",   "name": "Newmont Corp."},
        {"ticker": "NUE",   "name": "Nucor Corp."},
        {"ticker": "DOW",   "name": "Dow Inc."},
        {"ticker": "DD",    "name": "DuPont de Nemours"},
        {"ticker": "ECL",   "name": "Ecolab Inc."},
        {"ticker": "PPG",   "name": "PPG Industries"},
    ],
    "Utilities": [
        {"ticker": "NEE",   "name": "NextEra Energy"},
        {"ticker": "SO",    "name": "Southern Company"},
        {"ticker": "DUK",   "name": "Duke Energy"},
        {"ticker": "SRE",   "name": "Sempra"},
        {"ticker": "AEP",   "name": "American Electric Power"},
        {"ticker": "EXC",   "name": "Exelon Corp."},
        {"ticker": "XEL",   "name": "Xcel Energy"},
        {"ticker": "D",     "name": "Dominion Energy"},
        {"ticker": "WEC",   "name": "WEC Energy Group"},
    ],
    "Real Estate": [
        {"ticker": "PLD",   "name": "Prologis Inc."},
        {"ticker": "AMT",   "name": "American Tower"},
        {"ticker": "EQIX",  "name": "Equinix Inc."},
        {"ticker": "CCI",   "name": "Crown Castle Inc."},
        {"ticker": "PSA",   "name": "Public Storage"},
        {"ticker": "SPG",   "name": "Simon Property Group"},
        {"ticker": "O",     "name": "Realty Income Corp."},
        {"ticker": "DLR",   "name": "Digital Realty Trust"},
        {"ticker": "AVB",   "name": "AvalonBay Communities"},
        {"ticker": "WY",    "name": "Weyerhaeuser Co."},
    ],
}
